// all possible notes on a standard tuned guitar
const Notes = [
    "E2",
    "F2",
    "F#2",
    "G2",
    "G#2",
    "A2",
    "A#2",
    "B2",
    "C3",
    "C#3",
    "D3",
    "D#3",
    "E3",
    "F3",
    "F#3",
    "G3",
    "G#3",
    "A3",
    "A#3",
    "B3",
    "C4",
    "C#4",
    "D4",
    "D#4",
    "E4",
    "F4",
    "F#4",
    "G4",
    "G#4",
    "A4",
    "A#4",
    "B4",
    "C5",
    "C#5",
    "D5",
    "D#5",
    "E5",
    "F5",
    "F#5",
    "G5",
    "G#5",
    "A5",
    "A#5",
    "B5",
    "C6",
    "C#6",
    "D6",
] as const;
// all available frequencies of a standard tuned guitar
const frequencyMap: Record<Note, number> = {
    E2: 82.41,
    F2: 87.31,
    "F#2": 92.5,
    G2: 98,
    "G#2": 103.83,
    A2: 110,
    "A#2": 116.54,
    B2: 123.47,
    C3: 130.81,
    "C#3": 138.59,
    D3: 146.83,
    "D#3": 155.56,
    E3: 164.81,
    F3: 174.61,
    "F#3": 185,
    G3: 196,
    "G#3": 207.65,
    A3: 220,
    "A#3": 233.08,
    B3: 246.94,
    C4: 261.63,
    "C#4": 277.18,
    D4: 293.66,
    "D#4": 311.13,
    E4: 329.63,
    F4: 349.23,
    "F#4": 369.99,
    G4: 392,
    "G#4": 415.3,
    A4: 440,
    "A#4": 466.16,
    B4: 493.88,
    C5: 523.25,
    "C#5": 554.37,
    D5: 587.33,
    "D#5": 622.25,
    E5: 659.25,
    F5: 698.46,
    "F#5": 739.99,
    G5: 783.99,
    "G#5": 830.61,
    A5: 880,
    "A#5": 932.33,
    B5: 987.77,
    C6: 1046.5,
    "C#6": 1108.73,
    D6: 1174.66,
} as const;

// number of strings on a standard guitar
const guitarString = [1, 2, 3, 4, 5, 6] as const;
const GuitarStringToNotes = [
    // 1 (E)
    [
        "E4",
        "F4",
        "F#4",
        "G4",
        "G#4",
        "A4",
        "A#4",
        "B4",
        "C5",
        "C#5",
        "D5",
        "D#5",
        "E5",
        "F5",
        "F#5",
        "G5",
        "G#5",
        "A5",
        "A#5",
        "B5",
        "C6",
        "C#6",
        "D6",
    ],
    // 2 (B)
    [
        "B3",
        "C4",
        "C#4",
        "D4",
        "D#4",
        "E4",
        "F4",
        "F#4",
        "G4",
        "G#4",
        "A4",
        "A#4",
        "B4",
        "C5",
        "C#5",
        "D5",
        "D#5",
        "E5",
        "F5",
        "F#5",
        "G5",
        "G#5",
        "A5",
    ],
    // 3 (G)
    [
        "G3",
        "G#3",
        "A3",
        "A#3",
        "B3",
        "C4",
        "C#4",
        "D4",
        "D#4",
        "E4",
        "F4",
        "F#4",
        "G4",
        "G#4",
        "A4",
        "A#4",
        "B4",
        "C5",
        "C#5",
        "D5",
        "D#5",
        "E5",
        "F5",
    ],
    // 4 (D)
    [
        "D3",
        "D#3",
        "E3",
        "F3",
        "F#3",
        "G3",
        "G#3",
        "A3",
        "A#3",
        "B3",
        "C4",
        "C#4",
        "D4",
        "D#4",
        "E4",
        "F4",
        "F#4",
        "G4",
        "G#4",
        "A4",
        "A#4",
        "B4",
        "C5",
    ],
    // 5 (A)
    [
        "A2",
        "A#2",
        "B2",
        "C3",
        "C#3",
        "D3",
        "D#3",
        "E3",
        "F3",
        "F#3",
        "G3",
        "G#3",
        "A3",
        "A#3",
        "B3",
        "C4",
        "C#4",
        "D4",
        "D#4",
        "E4",
        "F4",
        "F#4",
        "G4",
    ],
    // 6 (E)
    [
        "E2",
        "F2",
        "F#2",
        "G2",
        "G#2",
        "A2",
        "A#2",
        "B2",
        "C3",
        "C#3",
        "D3",
        "D#3",
        "E3",
        "F3",
        "F#3",
        "G3",
        "G#3",
        "A3",
        "A#3",
        "B3",
        "C4",
        "C#4",
        "D4",
    ],
] as const;

export type Note = (typeof Notes)[number];
export type GuitarString = (typeof guitarString)[number];
export type Frequency = (typeof frequencyMap)[keyof typeof frequencyMap];

type GameApiInterface = {
    getNotesForString(name: (typeof guitarString)[number]): (typeof GuitarStringToNotes)[number];
    getRandomGuitarString(): (typeof guitarString)[number];
    getFrequencyFromNote(note: Note): (typeof frequencyMap)[Note];
    getRandomNoteForString(name: (typeof guitarString)[number]): Note;
};

export const GameApi: GameApiInterface = {
    getNotesForString(name) {
        return GuitarStringToNotes[name - 1];
    },

    getRandomGuitarString() {
        return guitarString[Math.floor(Math.random() * guitarString.length)];
    },
    getFrequencyFromNote(note: Note) {
        return frequencyMap[note];
    },
    getRandomNoteForString(name: (typeof guitarString)[number]) {
        const notes = GuitarStringToNotes[name - 1];
        return notes[Math.floor(Math.random() * notes.length)];
    },
};
